#.github/sync.yml
group:
  # 1st group for sync-up
  - files:
      - source: data/reports/factset_portfolio_summary_latest.csv
        dest:   data/stage1_raw/factset_portfolio_summary_latest.csv
      - source: data/reports/factset_detailed_report_latest.csv
        dest:   data/stage1_raw/factset_detailed_report_latest.csv
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
